export const searchableItems = [
  { type: 'page', title: 'Beranda', href: '/' },
  { type: 'page', title: 'Profil', href: '/profile' },
  { type: 'page', title: 'Layanan', href: '/layanan' },
  { type: 'page', title: 'Artikel', href: '/artikel' },
  { type: 'page', title: 'Kontak', href: '/kontak' },
  { type: 'page', title: 'Harga', href: '/harga' },
  { type: 'service', title: 'Penulisan Skripsi', href: '/harga?category=skripsi' },
  { type: 'service', title: 'Publikasi Jurnal', href: '/harga?category=publikasi-jurnal' },
  { type: 'service', title: 'Penulisan Artikel Jurnal Nasional Terakreditasi SINTA', href: '/harga?category=penulisan-artikel-sinta' },
  { type: 'service', title: 'Workshop Akademik', href: '/harga?category=workshop' },
  { type: 'service', title: 'Konsultasi Penelitian', href: '/harga?category=konsultasi' },
  { type: 'service', title: 'Mentoring Personal', href: '/harga?category=mentoring' },
  { type: 'service', title: 'Review Jurnal', href: '/harga?category=review' },
  { type: 'service', title: 'Editing Dokumen', href: '/harga?category=editing' },
  { type: 'service', title: 'Proofreading', href: '/harga?category=proofreading' },
  { type: 'service', title: 'Penerjemahan Dokumen', href: '/harga?category=translation' },
  { type: 'service', title: 'Analisis Data', href: '/harga?category=data-analysis' },
  { type: 'service', title: 'Statistik Penelitian', href: '/harga?category=statistics' },
  { type: 'service', title: 'Metodologi Penelitian', href: '/harga?category=methodology' },
  { type: 'service', title: 'Sistematika Penulisan', href: '/harga?category=writing-systematic' },
  { type: 'article', title: 'Tips Menulis Abstrak', href: '/artikel/tips-menulis-abstrak' },
  { type: 'article', title: 'Cara Memilih Jurnal', href: '/artikel/cara-memilih-jurnal' },
  { type: 'article', title: 'Metodologi Penelitian Kualitatif', href: '/artikel/metodologi-kualitatif' },
  { type: 'article', title: 'Metodologi Penelitian Kuantitatif', href: '/artikel/metodologi-kuantitatif' },
  { type: 'article', title: 'Cara Menulis Literature Review', href: '/artikel/literature-review' },
  { type: 'article', title: 'Tips Publikasi di Jurnal Internasional', href: '/artikel/publikasi-internasional' },
  { type: 'article', title: 'Mengatasi Plagiarisme', href: '/artikel/mengatasi-plagiarisme' },
  { type: 'article', title: 'Format Penulisan APA Style', href: '/artikel/apa-style' },
  { type: 'article', title: 'Format Penulisan Chicago Style', href: '/artikel/chicago-style' },
  { type: 'article', title: 'Cara Menulis Pendahuluan', href: '/artikel/pendahuluan' },
  { type: 'article', title: 'Cara Menulis Kesimpulan', href: '/artikel/kesimpulan' },
  { type: 'article', title: 'Teknik Wawancara Penelitian', href: '/artikel/teknik-wawancara' },
  { type: 'article', title: 'Analisis Data dengan SPSS', href: '/artikel/analisis-spss' },
  { type: 'article', title: 'Analisis Data dengan R', href: '/artikel/analisis-r' },
  { type: 'article', title: 'Validitas dan Reliabilitas', href: '/artikel/validitas-reliabilitas' },
  { type: 'article', title: 'Sampling Techniques', href: '/artikel/sampling-techniques' },
  { type: 'article', title: 'Ethical Considerations in Research', href: '/artikel/ethical-considerations' },
]