export const searchableItems = [
  { type: 'page', title: 'Beranda', href: '/' },
  { type: 'page', title: 'Profil', href: '/profile' },
  { type: 'page', title: 'Layanan', href: '/layanan' },
  { type: 'page', title: 'Artikel', href: '/artikel' },
  { type: 'page', title: 'Kontak', href: '/kontak' },
  { type: 'page', title: 'Harga', href: '/harga' },
  
  // Penulisan Skripsi - Updated packages
  { type: 'service', title: 'Penulisan Skripsi', href: '/harga?category=skripsi' },
  { type: 'service', title: 'Penulisan Skripsi From Scratch', href: '/harga?category=skripsi' },
  { type: 'service', title: 'Paket Semua Bab (1-5)', href: '/harga?category=skripsi' },
  { type: 'service', title: 'Per Bab Individual', href: '/harga?category=skripsi' },
  { type: 'service', title: 'Layanan Tambahan Skripsi', href: '/harga?category=skripsi' },
  { type: 'service', title: 'Layouting Skripsi', href: '/harga?category=skripsi' },
  { type: 'service', title: 'Proofreading Skripsi', href: '/harga?category=skripsi' },
  { type: 'service', title: 'Daftar Pustaka', href: '/harga?category=skripsi' },
  
  // Publikasi Jurnal - Updated with Sinta 1 & 2
  { type: 'service', title: 'Publikasi Jurnal', href: '/harga?category=publikasi-jurnal' },
  { type: 'service', title: 'ISSN Nasional Standar', href: '/harga?category=publikasi-jurnal' },
  { type: 'service', title: 'Sinta 6 Publikasi', href: '/harga?category=publikasi-jurnal' },
  { type: 'service', title: 'Sinta 5 Publikasi', href: '/harga?category=publikasi-jurnal' },
  { type: 'service', title: 'Sinta 4 Publikasi', href: '/harga?category=publikasi-jurnal' },
  { type: 'service', title: 'Sinta 3 Publikasi', href: '/harga?category=publikasi-jurnal' },
  { type: 'service', title: 'Sinta 2 Publikasi', href: '/harga?category=publikasi-jurnal' },
  { type: 'service', title: 'Sinta 1 Publikasi', href: '/harga?category=publikasi-jurnal' },
  
  // Workshop Akademik - Updated packages
  { type: 'service', title: 'Workshop Akademik', href: '/harga?category=workshop' },
  { type: 'service', title: 'Paket Pembicara & Modul', href: '/harga?category=workshop' },
  { type: 'service', title: 'Paket Full Package Workshop', href: '/harga?category=workshop' },
  { type: 'service', title: 'Webinar', href: '/harga?category=workshop' },
  { type: 'service', title: 'Seminar', href: '/harga?category=workshop' },
  { type: 'service', title: 'Guest Lecture', href: '/harga?category=workshop' },
  { type: 'service', title: 'Training Proposal', href: '/harga?category=workshop' },
  
  // Konsultasi Penelitian - Updated packages
  { type: 'service', title: 'Konsultasi Penelitian', href: '/harga?category=konsultasi' },
  { type: 'service', title: 'Basic Focus Konsultasi', href: '/harga?category=konsultasi' },
  { type: 'service', title: 'Standard Development', href: '/harga?category=konsultasi' },
  { type: 'service', title: 'Intensive Guidance', href: '/harga?category=konsultasi' },
  { type: 'service', title: 'Full Academic Support', href: '/harga?category=konsultasi' },
  { type: 'service', title: 'Mentoring Personal', href: '/harga?category=konsultasi' },
  { type: 'service', title: 'Konsultasi Gratis', href: '/kontak' },
  { type: 'service', title: 'Mentoring Deep 101 Session', href: '/harga?category=konsultasi' },
  
  // All You Can Request - New service
  { type: 'service', title: 'All You Can Request', href: '/harga?category=all-you-can-request' },
  { type: 'service', title: 'Custom Request', href: '/harga?category=all-you-can-request' },
  { type: 'service', title: 'Penyediaan Responden', href: '/harga?category=all-you-can-request' },
  { type: 'service', title: 'Layout Artikel', href: '/harga?category=all-you-can-request' },
  { type: 'service', title: 'Halaman Awal Skripsi', href: '/harga?category=all-you-can-request' },
  { type: 'service', title: 'Sitasi', href: '/harga?category=all-you-can-request' },
  { type: 'service', title: 'Cek Plagiarisme', href: '/harga?category=all-you-can-request' },
  { type: 'service', title: 'Terjemahan', href: '/harga?category=all-you-can-request' },
  { type: 'service', title: 'Editing', href: '/harga?category=all-you-can-request' },
  { type: 'service', title: 'Format Artikel Jurnal', href: '/harga?category=all-you-can-request' },
  { type: 'service', title: 'PPT Sidang', href: '/harga?category=all-you-can-request' },
  { type: 'service', title: 'Simulasi Sidang', href: '/harga?category=all-you-can-request' },
  
  // Articles
  { type: 'article', title: 'Tips Menulis Abstrak', href: '/artikel/tips-menulis-abstrak' },
  { type: 'article', title: 'Cara Memilih Jurnal', href: '/artikel/cara-memilih-jurnal' },
  { type: 'article', title: 'Metodologi Penelitian Kualitatif', href: '/artikel/metodologi-kualitatif' },
  { type: 'article', title: 'Metodologi Penelitian Kuantitatif', href: '/artikel/metodologi-kuantitatif' },
  { type: 'article', title: 'Cara Menulis Literature Review', href: '/artikel/literature-review' },
  { type: 'article', title: 'Tips Publikasi di Jurnal Internasional', href: '/artikel/publikasi-internasional' },
  { type: 'article', title: 'Mengatasi Plagiarisme', href: '/artikel/mengatasi-plagiarisme' },
  { type: 'article', title: 'Format Penulisan APA Style', href: '/artikel/apa-style' },
  { type: 'article', title: 'Format Penulisan Chicago Style', href: '/artikel/chicago-style' },
  { type: 'article', title: 'Cara Menulis Pendahuluan', href: '/artikel/pendahuluan' },
  { type: 'article', title: 'Cara Menulis Kesimpulan', href: '/artikel/kesimpulan' },
  { type: 'article', title: 'Teknik Wawancara Penelitian', href: '/artikel/teknik-wawancara' },
  { type: 'article', title: 'Analisis Data dengan SPSS', href: '/artikel/analisis-spss' },
  { type: 'article', title: 'Analisis Data dengan R', href: '/artikel/analisis-r' },
  { type: 'article', title: 'Validitas dan Reliabilitas', href: '/artikel/validitas-reliabilitas' },
  { type: 'article', title: 'Sampling Techniques', href: '/artikel/sampling-techniques' },
  { type: 'article', title: 'Ethical Considerations in Research', href: '/artikel/ethical-considerations' },
]